# Generated by Django 2.1 on 2018-10-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Cliente')),
                ('codigoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Mascota')),
            ],
        ),
    ]
