# Generated by Django 2.1 on 2018-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigoPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePersona', models.CharField(max_length=30)),
                ('emailPersona', models.EmailField(default='sincorreo@gmail.com', max_length=254)),
            ],
        ),
    ]
