# Generated by Django 2.1 on 2018-10-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=10)),
                ('perfil', models.CharField(default='Usuario', max_length=20)),
            ],
        ),
    ]
