# Generated by Django 2.1 on 2018-11-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('patio', models.BooleanField(default=False)),
            ],
        ),
    ]
