# Generated by Django 2.1 on 2018-09-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigoCliete', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('rutCliente', models.CharField(max_length=15)),
            ],
        ),
    ]
