# Generated by Django 2.1 on 2018-09-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_auto_20180926_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.Mascota')),
                ('codigoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.Persona')),
            ],
        ),
    ]
